services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo_app_db'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
